const APPROVAL_STATUS={
    'PENDING':'PENDING',
    'APPROVED':'APPROVED',
    'REJECTED':'REJECTED',
}
const REQUISITION_STATUS={
    'PENDING':'PENDING',
    'APPROVED':'APPROVED',
    'CLOSED':'CLOSED',
    'REJECTED':'REJECTED',
}
const ROLES= {
    HEAD_HR: 'HEAD_HR',
    PANELIST: 'PANELIST',
    FINANCE: 'FINANCE',
    BU_OWNER: 'BU_OWNER',
    HIRING_MANAGER: 'HIRING_MANAGER',
    HR_RECRUITER: 'HR_RECRUITER'
  }

module.exports={
    APPROVAL_STATUS,
    REQUISITION_STATUS,
    ROLES
}